nelmio_api_doc:
  documentation:
    info:
      title: My App
      description: My app api!
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api/v1 # Accepts routes under /api except /api/doc
