version: '3'

services:
  database:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  database_test:
    container_name: postgres_test
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  nginx:
    container_name: nginx
    image: nginx:1.24-alpine
    ports:
      - 3000:80
    volumes:
      - ./.docker/conf/nginx/booking.conf:/etc/nginx/conf.d/booking.conf
    depends_on:
      - database
