version: '3'

services:
  database:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  nginx:
    image: nginx:1.24-alpine
    ports:
      - 3000:80
    volumes:
      - ./.docker/conf/nginx/booking.conf:/etc/nginx/conf.d/booking.conf
    depends_on:
      - database
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app
